//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Celibate_Music_API_MAIN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DADEntities2 : DbContext
    {
        public DADEntities2()
            : base("name=DADEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer2177> Customer2177 { get; set; }
        public virtual DbSet<Interest2177> Interest2177 { get; set; }
        public virtual DbSet<Record2177> Record2177 { get; set; }
        public virtual DbSet<Sale2177> Sale2177 { get; set; }
    }
}
