CREATE TABLE [dbo].[Customer2177]
(
	[CUSTOMERID] INT,
	[NAME] NVARCHAR(50),
	[ADDRESS] NVARCHAR(100),
	[POSTCODE] INT,
	[INTERESTCODE] NVARCHAR(2),

	PRIMARY KEY(CUSTOMERID),

	FOREIGN KEY(INTERESTCODE) REFERENCES INTEREST2177
)
