CREATE TABLE [dbo].[Sale2177]
(
	[SALEDATE] DATE,
	[PRICE] DECIMAL,
	[CUSTOMERID] INT,
	[INTERESTCODE] NVARCHAR(2),
	[RECORDID] NVARCHAR(5),

	PRIMARY KEY(CUSTOMERID, SALEDATE, RECORDID),
	FOREIGN KEY(RECORDID) REFERENCES RECORD2177,
	FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER2177
)
