//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Celibate_Music_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record2177
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Record2177()
        {
            this.Sale2177 = new HashSet<Sale2177>();
        }
    
        public string ID { get; set; }
        public string TITLE { get; set; }
        public string PERFORMER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale2177> Sale2177 { get; set; }
    }
}
