//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Celibate_Music_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale2177
    {
        public System.DateTime SALEDATE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public int CUSTOMERID { get; set; }
        public string INTERESTCODE { get; set; }
        public string RECORDID { get; set; }
    
        public virtual Customer2177 Customer2177 { get; set; }
        public virtual Record2177 Record2177 { get; set; }
    }
}
